[package]
name = "spin-trigger"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[features]
llm = ["spin-llm-local"]
llm-metal = ["llm", "spin-llm-local/metal"]
llm-cublas = ["llm", "spin-llm-local/cublas"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.1.15", features = ["derive", "env"] }
ctrlc = { version = "3.2", features = ["termination"] }
dirs = "4"
futures = "0.3"
indexmap = "1"
logging = { path = "../logging" }
outbound-http = { path = "../outbound-http" }
outbound-redis = { path = "../outbound-redis" }
outbound-pg = { path = "../outbound-pg" }
outbound-mysql = { path = "../outbound-mysql" }
spin-common = { path = "../common" }
spin-key-value = { path = "../key-value" }
spin-key-value-azure = { path = "../key-value-azure" }
spin-key-value-redis = { path = "../key-value-redis" }
spin-key-value-sqlite = { path = "../key-value-sqlite" }
spin-sqlite = { path = "../sqlite" }
spin-sqlite-inproc = { path = "../sqlite-inproc" }
spin-sqlite-libsql = { path = "../sqlite-libsql" }
spin-world = { path = "../world" }
spin-llm = { path = "../llm" }
spin-llm-local = { path = "../llm-local", optional = true }
spin-llm-remote-http = { path = "../llm-remote-http" }
sanitize-filename = "0.4"
serde = "1.0.188"
serde_json = "1.0"
spin-app = { path = "../app" }
spin-config = { path = "../config" }
spin-core = { path = "../core" }
spin-loader = { path = "../loader" }
spin-manifest = { path = "../manifest" }
terminal = { path = "../terminal" }
tokio = { version = "1.23", features = ["fs"] }
toml = "0.5.9"
tracing = { workspace = true }
url = "2"
wasmtime = { workspace = true }
spin-componentize = { workspace = true }

[dev-dependencies]
libtest-mimic = "0.6.1"
snapbox = "0.4.12"
tempfile = "3.3.0"
toml = "0.5"
tokio = { version = "1.23", features = ["rt", "macros"] }

[[test]]
name = "ui"
path = "tests/ui.rs"
harness = false
